import { Resend } from 'resend';
import { logger } from '../config/logger';

// Use a placeholder if no key is provided in the environment
const resend = new Resend(process.env.RESEND_API_KEY || 're_123456789_placeholder');

export class EmailService {
  /**
   * Sends an email notification to the user when a job application is successfully submitted.
   */
  public async sendApplicationSuccessEmail(
    toEmail: string, 
    jobDetails: { company: string, role: string, url: string }, 
    coverLetter: string
  ): Promise<boolean> {
    
    if (!process.env.RESEND_API_KEY) {
      logger.warn(`✉️ Simulated Email (No API Key): Success notification for ${jobDetails.company} sent to ${toEmail}`);
      return true;
    }

    try {
      const data = await resend.emails.send({
        from: 'Blacken Job Agent <onboarding@resend.dev>', // Resend testing email
        to: [toEmail],
        subject: `✅ Application Submitted: ${jobDetails.company} - ${jobDetails.role}`,
        html: `
          <div style="font-family: sans-serif; max-w-2xl; margin: 0 auto; padding: 20px;">
            <h2 style="color: #10b981;">Application Successfully Submitted!</h2>
            <p>Your autonomous agent has successfully completed and submitted an application on your behalf.</p>
            
            <div style="background-color: #f4f4f5; padding: 15px; border-radius: 8px; margin: 20px 0;">
              <h3 style="margin-top: 0; color: #18181b;">Job Details</h3>
              <p><strong>Company:</strong> ${jobDetails.company}</p>
              <p><strong>Role:</strong> ${jobDetails.role}</p>
              <p><strong>Link:</strong> <a href="${jobDetails.url}">View Job Posting</a></p>
            </div>

            <h3 style="color: #18181b;">The Cover Letter I Wrote For You:</h3>
            <div style="background-color: #fafafa; padding: 15px; border-left: 4px solid #3b82f6; color: #3f3f46; white-space: pre-wrap;">
              ${coverLetter}
            </div>
            
            <p style="margin-top: 30px; color: #71717a; font-size: 12px;">
              This email was generated by your Blacken.ai Autonomous Agent.
            </p>
          </div>
        `,
      });

      logger.info(`✉️ Email sent successfully for ${jobDetails.company} (ID: ${data.data?.id})`);
      return true;
    } catch (error) {
      logger.error(`✉️ Failed to send email notification:`, error);
      return false;
    }
  }
}

export const emailService = new EmailService();
